version: "3"

services:

  gitlab:
    image: gitlab/gitlab-ce:13.9.3-ce.0
    volumes:
      - gitlab-var-config:/etc/gitlab
      - gitlab-var-logs:/var/log/gitlab
      - gitlab-var-data:/var/opt/gitlab
    networks:
      - intranet
    ports:
      # - "22:22"
      # - "80:80"
      # - "443:443"
      # Exposed for developers
      - "85:80"

  houston:
    environment: &houston-environment
      GITLAB_PROTO: "http"
      GITLAB_HOST: "gitlab"
      GITLAB_PORT: "80"
      GITLAB_ADMIN_PASSWORD: "development"
      GITLAB_REMOTE_URI: "http://gitlab"
      GITLAB_REMOTE_LOGIN_PAT: ""
      GIT_SSH_KEY: ""
      GIT_PUBLIC_NAME: "${GIT_PUBLIC_NAME}"
      GIT_EMAIL: "${GIT_EMAIL}"

  celery_beat:
    environment: *houston-environment

  celery_worker:
    environment: *houston-environment


networks:
  intranet:

volumes:
  gitlab-var-config:
  gitlab-var-logs:
  gitlab-var-data:
