version: "3.8"

services:

  db:
    image: postgres:10
    volumes:
      - db-pgdata-var:/var/lib/postgresql/data
      # DB initialization scripts
      - .dockerfiles/db/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      WBIA_DB_NAME: "${WBIA_DB_NAME}"
      WBIA_DB_USER: "${WBIA_DB_USER}"
      WBIA_DB_PASSWORD: "${WBIA_DB_PASSWORD}"
      WILDBOOK_DB_NAME: "${WILDBOOK_DB_NAME}"
      WILDBOOK_DB_USER: "${WILDBOOK_DB_USER}"
      WILDBOOK_DB_PASSWORD: "${WILDBOOK_DB_PASSWORD}"
      HOUSTON_DB_NAME: "${HOUSTON_DB_NAME}"
      HOUSTON_DB_USER: "${HOUSTON_DB_USER}"
      HOUSTON_DB_PASSWORD: "${HOUSTON_DB_PASSWORD}"
    networks:
      - intranet

  redis:
    image: redis:latest
    volumes:
      - redis-var:/data
    networks:
      - intranet

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    environment:
      "discovery.type": single-node
    ports:
      # development exposure, not exposed in production
      - 9200:9200
      - 9300:9300
    # volumes:
    #   - es-var:/usr/share/elasticsearch/data
    networks:
      - intranet

  acm:
    # https://github.com/WildMeOrg/wildbook-ia
    image: wildme/wbia:latest
    depends_on:
      - db
    command: ["--db-uri", "${WBIA_DB_URI}"]
    networks:
      - intranet
    ports:
      # FIXME: exposed for developer verification
      - "82:5000"
    volumes:
      - acm-database-var:/data/db
      - acm-cache-var:/cache
    environment:
      WBIA_DB_URI: "${WBIA_DB_URI}"
      HOUSTON_CLIENT_ID: "${HOUSTON_CLIENT_ID}"
      HOUSTON_CLIENT_SECRET: "${HOUSTON_CLIENT_SECRET}"

  houston:
    # https://github.com/WildMeOrg/houston
    image: wildme/houston:latest
    build: &houston-build
      context: .
      target: main
    command: [ "wait-for", "db:5432", "--", "wait-for", "--timeout=60", "elasticsearch:9200", "--", "invoke", "app.run", "--host", "0.0.0.0" ]
    networks:
      - intranet
      - frontend
    ports:
      # FIXME: exposed for developer verification
      - "83:5000"
    environment: &houston-environment
      HOUSTON_APP_CONTEXT: mws
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
      TEST_DATABASE_URI: "${TEST_DATABASE_URI}"
      ACM_AUTHENTICATIONS_URI__DEFAULT: "${ACM_AUTHENTICATIONS_URI__DEFAULT}"
      ELASTICSEARCH_HOSTS: "${ELASTICSEARCH_HOSTS}"
      HOUSTON_URL: "${HOUSTON_URL}"
      REDIS_HOST: redis
      OAUTH_CLIENT_ID: "${HOUSTON_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${HOUSTON_CLIENT_SECRET}"
      OAUTH_USER_EMAIL: "${OAUTH_USER_EMAIL}"
      WILDBOOK_DB_HOST: "${WILDBOOK_DB_HOST}"
      WILDBOOK_DB_NAME: "${WILDBOOK_DB_NAME}"
      WILDBOOK_DB_USER: "${WILDBOOK_DB_USER}"
      WILDBOOK_DB_PASSWORD: "${WILDBOOK_DB_PASSWORD}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/api/v1/site-info/heartbeat"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes: &houston-volumes
      - houston-var:/data
      # These are added for development. Do not mount these in production.
      - .dockerfiles/docker-entrypoint.sh:/docker-entrypoint.sh
      - .dockerfiles/docker-entrypoint-init.d.mws:/docker-entrypoint-init.d
      - .dockerfiles/docker-entrypoint-always-init.d:/docker-entrypoint-always-init.d
      # FIXME: pull in development code while working on bringing up the container
      - .:/code

  celery_beat:
    image: wildme/houston:latest
    build: *houston-build
    command: [ "wait-for", "db:5432", "--", "celery", "-A", "app.extensions.celery.celery", "beat", "-s", "/data/var/celerybeat-schedule", "-l", "DEBUG"]
    networks:
      - intranet
    depends_on:
      houston:
        condition: service_healthy
    environment: *houston-environment
    volumes: *houston-volumes

  celery_worker:
    image: wildme/houston:latest
    build: *houston-build
    command: [ "wait-for", "db:5432", "--", "celery", "-A", "app.extensions.celery.celery", "worker", "-l", "DEBUG"]
    networks:
      - intranet
    depends_on:
      houston:
        condition: service_healthy
    environment: *houston-environment
    volumes: *houston-volumes

  dev-frontend:
    # this component is intended to only be used in development
    image: node:lts
    working_dir: /code
    entrypoint: "/docker-entrypoint.sh"
    networks:
      - intranet
    environment:
      HOST: "0.0.0.0"
      # See port served by 'www' component (i.e. the reverse proxy)
      PORT: "84"
    volumes:
      - .dockerfiles/dev-frontend/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./_frontend.mws:/code

  www:
    image: nginx:latest
    networks:
      - intranet
      - frontend
    ports:
      - "84:80"
    volumes:
      - .dockerfiles/www/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  intranet:
  frontend:

volumes:
  db-pgdata-var:
  # es-var:
  redis-var:
  acm-database-var:
  acm-cache-var:
  houston-var:
