[tool.black]
line-length = 90
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git,
    \_assets,
    \_db,
    \_frrontend,
    clients,
    deploy,
    Houston.egg-info,
    virtualenv
)/
'''
