version: "3"

services:
  gitlab:
    deploy:
      replicas: 0

  houston:
    environment: &houston-environment
      GITLAB_REMOTE_URI: "-"

  celery_beat:
    environment: *houston-environment

  celery_worker:
    environment: *houston-environment
