name: Docker

on: push

jobs:
  # Push container image to GitHub Packages and Docker Hub.
  # See also https://docs.docker.com/docker-hub/builds/
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      # Build images
      - name: Install package and build image
        run: |
          ./scripts/build.sh

      # Log into container registries
      - name: Log into Docker Hub
        run: echo "${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}" | docker login -u wildmebot --password-stdin

      - name: Log into GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      # ############################################################
      # Push Tagged image to registries
      - name: Push to GitHub Packages
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's#.*/v##')
          ./scripts/publish.sh -t ${VERSION} -r docker.pkg.github.com houston
      - name: Push to Docker Hub
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's#.*/v##')
          ./scripts/publish.sh -t ${VERSION} houston

      # ############################################################
      # Push latest image to registries
      - name: Push to GitHub Packages
        if: github.ref == 'refs/heads/develop'
        run: |
          ./scripts/publish.sh -t latest -r docker.pkg.github.com houston
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/develop'
        run: |
          ./scripts/publish.sh -t latest houston
