name: GitLab Cleanup
on:
  schedule:
    - cron: '0 2 * * *' # Every day at 02:00
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/gitlab-cleanup.yml'
  pull_request:
    paths:
      - '.github/workflows/gitlab-cleanup.yml'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Use the same Python version used the Dockerfile
        python-version: [3.9]
    env:
      GITLAB_REMOTE_LOGIN_PAT: ${{ secrets.GITLAB_REMOTE_LOGIN_PAT }}
      GITLAB_REMOTE_URI: "https://sub.dyn.wildme.io/"
    steps:
      # Checkout and env setup
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install libmagic on Ubuntu
        run: |
          sudo apt install libmagic1

      - name: Build frontend and swagger ui
        run: |
          ./scripts/codex/build.frontend.sh
          ./scripts/swagger/build.frontend.sh

      - name: Configure gitlab remote login pat
        run: |
          set -ex
          pip install "python-dotenv[cli]"
          # Set secrets
          dotenv -f .env set GITLAB_REMOTE_LOGIN_PAT -- "${GITLAB_REMOTE_LOGIN_PAT}"
          dotenv -f .env set GITLAB_REMOTE_URI -- "${GITLAB_REMOTE_URI}"
          # After using dotenv, file is only readable by owner, need to
          # give everyone (e.g. docker) read access to avoid permission
          # error
          chmod +r .env

      - name: Run docker-compose
        run: |
          set -ex
          docker-compose up -d db redis edm houston acm elasticsearch

      - name: Check the state of the containers
        run: |
          set -ex
          # Wait until houston is up
          while sleep 15
          do
            docker-compose logs houston | tail
            docker-compose ps
            if [ -n "$(docker-compose ps | grep Exit)" ]
            then
              exit 1
            fi
            # Wait for houston to be ready
            wget --tries=1 -O - http://localhost:83/api/v1/users/admin_user_initialized && break
          done

      - name: Cleanup
        run: |
          docker-compose exec -T houston invoke codex.consistency.cleanup-gitlab
