name: Nightly
on:
  schedule:
    - cron: '0 16 * * *' # Every day at 16:00 UTC (~09:00 PT)
  push:
    paths:
      - '.github/workflows/nightly.yml'
      - 'scripts/**'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
      - 'scripts/**'

jobs:
  image_build:
    name: DevOps nightly image build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'schedule'
        with:
          ref: main

      - uses: actions/checkout@v2
        if: github.event_name != 'schedule'

      # Build images
      - name: Build docker image
        run: |
          ./scripts/codex/build.docker.sh

      # Log into image registries
      - name: Log into Docker Hub
        run: echo "${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}" | docker login -u wildmebot --password-stdin
      - name: Log into GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      # Push images out to image registries
      - name: Push to GitHub Packages
        run: ./scripts/utils/publish.sh -t nightly -r docker.pkg.github.com codex
      - name: Push to Docker Hub
        if: github.event_name == 'schedule'
        run: ./scripts/utils/publish.sh -t nightly codex

      # Notify status in Slack
      - name: Slack Notification
        if: failure() && github.event_name == 'schedule'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'nightly build of the *container image* failed :sob:'
          SLACK_USERNAME: "Nightly"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  ensure_frontend_build:
    # Used to ensure the frontend will continuously build
    name: Ensure frontend code builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'schedule'
        with:
          ref: main

      - uses: actions/checkout@v2
        if: github.event_name != 'schedule'

      - name: Build the frontend
        run: |
          ./scripts/codex/build.frontend.sh

      # Notify status in Slack
      - name: Slack Notification
        if: failure() && github.event_name == 'schedule'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'nightly build to ensure the *frontend* builds failed :astonished:'
          SLACK_USERNAME: "Nightly"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  ensure_swagger_ui_build:
    # Used to ensure the frontend will continuously build
    name: Ensure swagger UI code builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'schedule'
        with:
          ref: main

      - uses: actions/checkout@v2
        if: github.event_name != 'schedule'

      - name: Build the swagger UI
        run: |
          ./scripts/swagger/build.frontend.sh

      # Notify status in Slack
      - name: Slack Notification
        if: failure() && github.event_name == 'schedule'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dev-houston
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.slack-edge.com/2020-03-02/965719891842_db87aa21ccb61076f236_44.png
          SLACK_MESSAGE: 'nightly build to ensure the *swagger UI* builds failed :face_with_raised_eyebrow:'
          SLACK_USERNAME: "Nightly"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
